### ISSUE TITLE
FileNotFoundError:T_applanix_aeva.txt not found.

### ISSUE THREAD

**Issue by YLRK** [cheneyuwu/vtr_testing_radar#9]
When I run the following command:

```bash
bash src/vtr_testing_radar/script/parallel_test_localization.sh 
```

I will be prompted that the file does not exist in the dataset file.

```bash
FileNotFoundError: ~/ASRL/data/boreas/sequences/boreas-2020-11-26-13-58/calib/T_applanix_aeva.txt not found.
```

May I ask how to obtain this file? Many thanks.

**Comment by YLRK** [comment]
At the same time, the following error prompt will appear:
```bash
FileNotFoundError: [Errno 2] No such file or directory: '/home/ylds-x/ASRL/data/boreas/sequences/boreas-2020-12-04-14-00/applanix/radar_poses.csv'
```

After checking the data set, the file does not exist.Only one imv.csv file exists
```bash
$ aws s3 ls s3://boreas/boreas-2020-12-04-14-00/applanix/
2021-10-21 01:51:13   28924015 imu.csv
```

**Comment by cheneyuwu** [comment]
Hi - sorry for the late reply. This repo (and the Boreas dataset repo) needs more clean up -  hopefully I can work on it mid-September.

**Comment by cheneyuwu** [comment]
further updates will be given in the vtr3 repo: https://github.com/utiasASRL/vtr3
